// Wallets Action Types
export const UPDATE_EXCHANGES = 'WALLETS-UPDATE-EXCHANGES';
export const SELECT_CURRENCY = 'WALLETS-SELECT-CURRENCY';
export const UPDATE_RATES = 'WALLETS-UPDATE-RATES';
export const EXCHANGE = 'WALLETS-EXCHANGE';
